---
title: "label-scraping"
output: html_document
---
```{r}
library(tidyverse)
library(jsonlite)
```

```{r}
#Import json file
json_raw <- fromJSON("https://api.census.gov/data/2021/cps/asec/mar/variables.json") 

#convert to a dataframe
cps_raw <- enframe(unlist(json_raw))

#separate out variable name and data type into separate columns
cps_raw <- cps_raw %>% separate(name, into = c(paste0("x", 1:3)))

#check number of unique variables in data set (502)
cps_unique <- unique(cps_raw$x2)
length(cps_unique)

#filter so you are only getting variables and their labels
cps_df <- cps_raw %>%
   select(x2, x3, value) %>%
   filter(x3 == "label")

#rename columns
cps_df <- cps_df %>% 
  select(x2, value)%>% 
  rename(
    Variable = x2,
    Label = value
    )
#check results
print(head(cps_df, 10))

#Check number of variables in dataframe to make sure they match 502
length(cps_df$Variable)
#Returns 389

#check that no null labels
sum(is.na(cps_df$Label))

#Which variables not in label df (113 total)
cps_missing <- subset(cps_raw, !(x2 %in% cps_df$Variable))
cps_missing <- unique(missing$x2)
cps_missing
```